version: 2

models:
  - name: fct_airline_performance
    description: >
      Airline performance fact table with punctuality and delay metrics.
      Supports KPIs: Punctuality, Airline performance
    columns:
      - name: airline_key
        description: Foreign key to dim_airline
        tests:
          - not_null
      - name: total_flights
        description: Total number of flights (including deleted/cancelled)
      - name: active_flights
        description: Non-deleted flights
      - name: completed_flights
        description: Flights with actual times (landed/departed)
      - name: on_time_flights
        description: Flights that were on-time (delay <= 15 minutes)
      - name: on_time_percentage
        description: Percentage of completed flights that were on-time
      - name: avg_delay_minutes
        description: Average delay in minutes
      - name: median_delay_minutes
        description: Median delay in minutes (more robust than average)
      - name: domestic_flights
        description: Count of domestic Swedish flights
      - name: international_flights
        description: Count of international flights

  - name: fct_airport_daily_traffic
    description: >
      Daily airport traffic fact table with capacity utilization metrics.
      Supports KPI: Capacity utilization
    columns:
      - name: airport_daily_key
        description: Surrogate key (airport + date + flight_type)
        tests:
          - unique
          - not_null
      - name: airport_iata
        description: Airport IATA code
        tests:
          - not_null
      - name: flight_date
        description: Date of flight operations
        tests:
          - not_null
      - name: flight_type
        description: Flight type (arrival or departure)
      - name: flight_count
        description: Total active flights (excluding deleted)
      - name: domestic_flights
        description: Count of domestic flights
      - name: international_flights
        description: Count of international flights
      - name: on_time_percentage
        description: Percentage of completed flights that were on-time
      - name: unique_airlines
        description: Number of unique airlines operating

  - name: fct_terminal_performance
    description: >
      Terminal efficiency fact table.
      Supports KPI: Terminal efficiency
    columns:
      - name: terminal_performance_key
        description: Surrogate key (terminal + flight_type + date)
        tests:
          - unique
          - not_null
      - name: terminal
        description: Terminal identifier
        tests:
          - not_null
      - name: flight_type
        description: Flight type (arrival or departure)
      - name: flight_date
        description: Date of operations
      - name: flight_count
        description: Total flights through this terminal
      - name: gates_used
        description: Number of unique gates used
      - name: on_time_percentage
        description: Percentage of on-time flights
      - name: avg_delay_minutes
        description: Average delay in minutes

  - name: fct_gate_utilization
    description: >
      Gate management and utilization fact table.
      Supports KPI: Gate management
    columns:
      - name: gate_utilization_key
        description: Surrogate key (terminal + gate + flight_type + date)
        tests:
          - unique
          - not_null
      - name: terminal
        description: Terminal identifier
      - name: gate
        description: Gate identifier
        tests:
          - not_null
      - name: flight_type
        description: Flight type (arrival or departure)
      - name: flight_date
        description: Date of operations
      - name: flight_count
        description: Total flights using this gate
      - name: unique_airlines
        description: Number of different airlines using this gate
      - name: on_time_percentage
        description: Percentage of on-time flights at this gate

  - name: fct_baggage_performance
    description: >
      Baggage handling performance fact table.
      Supports KPI: Baggage handling
    columns:
      - name: baggage_performance_key
        description: Surrogate key (baggage_claim_unit + airline + date)
        tests:
          - unique
          - not_null
      - name: baggage_claim_unit
        description: Baggage carousel identifier
        tests:
          - not_null
      - name: airline_iata
        description: Airline IATA code
      - name: flight_date
        description: Date of operations
      - name: flights_with_baggage_data
        description: Count of flights with complete baggage timing data
      - name: avg_baggage_handling_minutes
        description: Average time from first to last bag delivery
      - name: median_baggage_handling_minutes
        description: Median baggage handling time
      - name: avg_flight_delay_minutes
        description: Average flight delay (to correlate with baggage delays)

  - name: fct_hourly_traffic
    description: >
      Hourly traffic patterns fact table.
      Supports KPI: Peak hours
    columns:
      - name: hourly_traffic_key
        description: Surrogate key (hour + time_period + flight_type)
        tests:
          - unique
          - not_null
      - name: flight_hour
        description: Hour of day (0-23)
        tests:
          - not_null
      - name: flight_time_period
        description: Time period classification (Morning, Afternoon, Evening, Night)
      - name: flight_type
        description: Flight type (arrival or departure)
      - name: flight_count
        description: Total active flights in this hour
      - name: domestic_flights
        description: Count of domestic flights
      - name: international_flights
        description: Count of international flights
      - name: avg_delay_minutes
        description: Average delay for completed flights in this hour
      - name: on_time_flights
        description: Count of on-time flights
      - name: unique_airlines
        description: Number of unique airlines operating in this hour
