version: 2

models:
  - name: dim_airport
    description: Airport dimension table with Swedish Swedavia airports
    columns:
      - name: airport_key
        description: Surrogate key for airport dimension
        tests:
          - unique
          - not_null
      - name: airport_iata
        description: IATA airport code
        tests:
          - unique
          - not_null
      - name: airport_name
        description: Full airport name

  - name: fct_airport_daily_traffic
    description: >
      Daily airport traffic fact table with capacity utilization metrics.
      Supports KPI: Capacity utilization
    columns:
      - name: airport_daily_key
        description: Surrogate key (airport + date + flight_type)
        tests:
          - unique
          - not_null
      - name: airport_iata
        description: Airport IATA code
        tests:
          - not_null
      - name: flight_date
        description: Date of flight operations
        tests:
          - not_null
      - name: flight_type
        description: Flight type (arrival or departure)
      - name: flight_count
        description: Total active flights (excluding deleted)
      - name: domestic_flights
        description: Count of domestic flights
      - name: international_flights
        description: Count of international flights
      - name: on_time_percentage
        description: Percentage of completed flights that were on-time
      - name: unique_airlines
        description: Number of unique airlines operating

